name: "Check if version is published on NuGet"
author: "Arbeidstilsynet"
description: "Checks if the given package version is already published on a given source"

inputs:
  name:
    description: "The package name"
    required: true
  version:
    description: "The package version"
    required: true
  source-feed:
    description: "The source feed to check against. Must match a key in your `nuget.config`."
    default: "nuget.org"
  dotnet-version:
    description: "The version of dotnet to use"
    default: "8.0.x"
  config-file:
    description: 'Optional NuGet.config location, if your NuGet.config isn''t located in the root of the repo.'

outputs:
  published:
    description: "true if the version is already published, false otherwise"
    value: ${{ steps.nuget_version_check.outputs.published }}
  last_version:
    description: "The last stable version published on the source feed (empty if none)"
    value: ${{ steps.nuget_version_check.outputs.last_version }}
  last_prerelease_version:
    description: "The last prerelease version published on the source feed (empty if none)"
    value: ${{ steps.nuget_version_check.outputs.last_prerelease_version }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        config-file: ${{ inputs.config-file }}
    - name: Check if version is already published on NuGet
      id: nuget_version_check
      shell: bash
      run: |
        NAME="${{ inputs.name }}"
        VERSION="${{ inputs.version }}"
        SOURCE_FEED="${{ inputs.source-feed }}"

        SEARCH=$(dotnet package search "$NAME" --exact-match --prerelease --format json)
        echo "$SEARCH"

        # Get all versions for the package from the selected feed
        ALL_VERSIONS=$(echo "$SEARCH" | jq -r --arg SOURCE_FEED "$SOURCE_FEED" '.searchResult[] | select(.sourceName==$SOURCE_FEED) | .packages[] | .version' | sort -Vr)

        # Check if the requested version exists
        if echo "$ALL_VERSIONS" | grep -Fxq "$VERSION"; then
          echo "published=true" >> $GITHUB_OUTPUT
        else
          echo "published=false" >> $GITHUB_OUTPUT
        fi

        # Find the last stable version (no hyphen)
        LAST_VERSION=$(echo "$ALL_VERSIONS" | grep -v '-' | head -n 1 || true)
        echo "last_version=$LAST_VERSION" >> $GITHUB_OUTPUT

        # Find the last prerelease version (has hyphen)
        LAST_PRERELEASE_VERSION=$(echo "$ALL_VERSIONS" | grep '-' | head -n 1 || true)
        echo "last_prerelease_version=$LAST_PRERELEASE_VERSION" >> $GITHUB_OUTPUT
